name: CI
on:
  pull_request:
    types: [opened, assigned, synchronize]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.9'
      - uses: julia-actions/cache@v1
        with:
          cache-packages: "false"
      - uses: julia-actions/julia-buildpkg@v1
      # - name: Setup Rclone
      #   uses: AnimMouse/setup-rclone@v1
      #   with:
      #     rclone_config: ${{ secrets.RCLONE_CONFIG }}
      - name: Setup Test dependencies
        run: julia --project=. -e 'using RKM'
      - uses: julia-actions/julia-runtest@v1
      # - name: Docs Build and deploy
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
      #   run: julia --project=. docs/make.jl
